[project]
name = "marker_env"
version = "0.1.0"
description = ""
readme = "Readme.md"
requires-python = ">=3.11"
dependencies = [
  "marker-pdf[full]", # https://github.com/datalab-to/marker
  "psutil", # for `./task/Process-Folder.ps1`
  "torch",
  "torchvision",
]

[tool.uv.sources]
marker-pdf  = { path = "./lib/marker" } # Need to download, edit, compile, and install it.
# Please refer to <https://pytorch.org/get-started/locally/> and select the appropriate index.
torch       = { index = "pytorch-cuda126" }
torchvision = { index = "pytorch-cuda126" }
# torch       = { index = "pytorch-cuda130" }
# torchvision = { index = "pytorch-cuda130" }

[[tool.uv.index]]
name = "pytorch-cuda126"
url = "https://download.pytorch.org/whl/cu126" 
explicit = true

[[tool.uv.index]]
name = "pytorch-cuda130"
url = "https://download.pytorch.org/whl/cu130" 
explicit = true

[project.optional-dependencies]
marker_gui = [ # https://github.com/datalab-to/marker#interactive-app
  "streamlit>=1.53.0",
  "streamlit-ace>=0.1.1",
]
